import '../models/product_model.dart';

class MockData {
  static final List<Product> mockProducts = [
    Product(
      id: 1,
      title: 'Wireless Headphones',
      price: 99.99,
      description: 'High-quality wireless headphones with noise cancellation and 30-hour battery life.',
      category: 'electronics',
      image: 'https://via.placeholder.com/200?text=Headphones',
      rating: Rating(rate: 4.5, count: 120),
    ),
    Product(
      id: 2,
      title: 'Casual T-Shirt',
      price: 29.99,
      description: 'Comfortable cotton t-shirt perfect for everyday wear. Available in multiple colors.',
      category: 'clothing',
      image: 'https://via.placeholder.com/200?text=T-Shirt',
      rating: Rating(rate: 4.2, count: 85),
    ),
    Product(
      id: 3,
      title: 'Smartphone Stand',
      price: 15.99,
      description: 'Adjustable smartphone stand compatible with all devices. Perfect for desk or travel.',
      category: 'electronics',
      image: 'https://via.placeholder.com/200?text=Phone+Stand',
      rating: Rating(rate: 4.7, count: 210),
    ),
    Product(
      id: 4,
      title: 'Blue Denim Jeans',
      price: 59.99,
      description: 'Classic blue denim jeans with comfortable fit. Perfect for casual occasions.',
      category: 'clothing',
      image: 'https://via.placeholder.com/200?text=Jeans',
      rating: Rating(rate: 4.3, count: 150),
    ),
    Product(
      id: 5,
      title: 'USB-C Charging Cable',
      price: 12.99,
      description: 'High-speed USB-C cable with fast charging support. 2-meter length.',
      category: 'electronics',
      image: 'https://via.placeholder.com/200?text=USB+Cable',
      rating: Rating(rate: 4.6, count: 300),
    ),
    Product(
      id: 6,
      title: 'Winter Jacket',
      price: 89.99,
      description: 'Warm and stylish winter jacket with water-resistant material.',
      category: 'clothing',
      image: 'https://via.placeholder.com/200?text=Jacket',
      rating: Rating(rate: 4.4, count: 95),
    ),
    Product(
      id: 7,
      title: 'Portable Speaker',
      price: 49.99,
      description: 'Compact Bluetooth speaker with excellent sound quality and 12-hour battery.',
      category: 'electronics',
      image: 'https://via.placeholder.com/200?text=Speaker',
      rating: Rating(rate: 4.5, count: 180),
    ),
    Product(
      id: 8,
      title: 'Leather Wallet',
      price: 39.99,
      description: 'Premium leather wallet with multiple card slots and coin pocket.',
      category: 'accessories',
      image: 'https://via.placeholder.com/200?text=Wallet',
      rating: Rating(rate: 4.8, count: 240),
    ),
    Product(
      id: 9,
      title: 'Running Shoes',
      price: 79.99,
      description: 'Comfortable running shoes with superior cushioning and breathable material.',
      category: 'clothing',
      image: 'https://via.placeholder.com/200?text=Running+Shoes',
      rating: Rating(rate: 4.6, count: 320),
    ),
    Product(
      id: 10,
      title: 'Wireless Mouse',
      price: 34.99,
      description: 'Ergonomic wireless mouse with precision tracking and 18-month battery life.',
      category: 'electronics',
      image: 'https://via.placeholder.com/200?text=Wireless+Mouse',
      rating: Rating(rate: 4.4, count: 275),
    ),
    Product(
      id: 11,
      title: 'Sunglasses',
      price: 89.99,
      description: 'UV-protective sunglasses with polarized lenses and stylish design.',
      category: 'accessories',
      image: 'https://via.placeholder.com/200?text=Sunglasses',
      rating: Rating(rate: 4.7, count: 150),
    ),
    Product(
      id: 12,
      title: 'Coffee Maker',
      price: 59.99,
      description: 'Programmable coffee maker with thermal carafe and auto-brew timer.',
      category: 'electronics',
      image: 'https://via.placeholder.com/200?text=Coffee+Maker',
      rating: Rating(rate: 4.5, count: 190),
    ),
    Product(
      id: 13,
      title: 'Yoga Mat',
      price: 29.99,
      description: 'Non-slip yoga mat with carrying strap. Perfect for fitness and meditation.',
      category: 'clothing',
      image: 'https://via.placeholder.com/200?text=Yoga+Mat',
      rating: Rating(rate: 4.3, count: 210),
    ),
    Product(
      id: 14,
      title: 'Bluetooth Keyboard',
      price: 69.99,
      description: 'Compact wireless keyboard compatible with multiple devices. Rechargeable battery.',
      category: 'electronics',
      image: 'https://via.placeholder.com/200?text=BT+Keyboard',
      rating: Rating(rate: 4.5, count: 180),
    ),
    Product(
      id: 15,
      title: 'Watch Band',
      price: 19.99,
      description: 'Replacement watch band in various colors. Compatible with most smartwatches.',
      category: 'accessories',
      image: 'https://via.placeholder.com/200?text=Watch+Band',
      rating: Rating(rate: 4.2, count: 130),
    ),
    Product(
      id: 16,
      title: 'Desk Lamp',
      price: 44.99,
      description: 'LED desk lamp with adjustable brightness and color temperature control.',
      category: 'electronics',
      image: 'https://via.placeholder.com/200?text=Desk+Lamp',
      rating: Rating(rate: 4.6, count: 220),
    ),
    Product(
      id: 17,
      title: 'Cotton Socks Pack',
      price: 14.99,
      description: 'Comfortable 5-pack of cotton socks in assorted colors.',
      category: 'clothing',
      image: 'https://via.placeholder.com/200?text=Socks',
      rating: Rating(rate: 4.4, count: 165),
    ),
    Product(
      id: 18,
      title: 'Phone Case',
      price: 24.99,
      description: 'Durable protective phone case with shock absorption technology.',
      category: 'accessories',
      image: 'https://via.placeholder.com/200?text=Phone+Case',
      rating: Rating(rate: 4.5, count: 290),
    ),
    Product(
      id: 19,
      title: 'Webcam',
      price: 79.99,
      description: '1080p HD webcam with built-in microphone for video calls and streaming.',
      category: 'electronics',
      image: 'https://via.placeholder.com/200?text=Webcam',
      rating: Rating(rate: 4.7, count: 240),
    ),
    Product(
      id: 20,
      title: 'Scarf',
      price: 34.99,
      description: 'Lightweight and versatile scarf perfect for any season.',
      category: 'clothing',
      image: 'https://via.placeholder.com/200?text=Scarf',
      rating: Rating(rate: 4.3, count: 105),
    ),
    // Men's Products
    Product(
      id: 21,
      title: 'Men\'s Formal Shirt',
      price: 49.99,
      description: 'Professional formal shirt suitable for office and special occasions.',
      category: 'men',
      image: 'https://via.placeholder.com/200?text=Men+Shirt',
      rating: Rating(rate: 4.5, count: 180),
    ),
    Product(
      id: 22,
      title: 'Men\'s Leather Belt',
      price: 44.99,
      description: 'Genuine leather belt with classic buckle design.',
      category: 'men',
      image: 'https://via.placeholder.com/200?text=Men+Belt',
      rating: Rating(rate: 4.6, count: 220),
    ),
    Product(
      id: 23,
      title: 'Men\'s Sports Shoes',
      price: 89.99,
      description: 'High-performance sports shoes designed for active lifestyle.',
      category: 'men',
      image: 'https://via.placeholder.com/200?text=Men+Sports+Shoes',
      rating: Rating(rate: 4.7, count: 310),
    ),
    Product(
      id: 24,
      title: 'Men\'s Polo T-Shirt',
      price: 39.99,
      description: 'Classic polo t-shirt in premium cotton blend.',
      category: 'men',
      image: 'https://via.placeholder.com/200?text=Men+Polo',
      rating: Rating(rate: 4.4, count: 165),
    ),
    Product(
      id: 25,
      title: 'Men\'s Chino Pants',
      price: 64.99,
      description: 'Comfortable chino pants perfect for casual and semi-formal occasions.',
      category: 'men',
      image: 'https://via.placeholder.com/200?text=Men+Chinos',
      rating: Rating(rate: 4.3, count: 140),
    ),
    Product(
      id: 26,
      title: 'Men\'s Blazer',
      price: 129.99,
      description: 'Stylish blazer for professional and formal events.',
      category: 'men',
      image: 'https://via.placeholder.com/200?text=Men+Blazer',
      rating: Rating(rate: 4.8, count: 95),
    ),
    // Women's Products
    Product(
      id: 27,
      title: 'Women\'s Dress',
      price: 79.99,
      description: 'Elegant casual dress perfect for various occasions.',
      category: 'women',
      image: 'https://via.placeholder.com/200?text=Women+Dress',
      rating: Rating(rate: 4.6, count: 245),
    ),
    Product(
      id: 28,
      title: 'Women\'s Heels',
      price: 84.99,
      description: 'Comfortable yet stylish heels for any occasion.',
      category: 'women',
      image: 'https://via.placeholder.com/200?text=Women+Heels',
      rating: Rating(rate: 4.5, count: 190),
    ),
    Product(
      id: 29,
      title: 'Women\'s Handbag',
      price: 99.99,
      description: 'Luxury handbag with premium materials and elegant design.',
      category: 'women',
      image: 'https://via.placeholder.com/200?text=Women+Handbag',
      rating: Rating(rate: 4.7, count: 280),
    ),
    Product(
      id: 30,
      title: 'Women\'s Blouse',
      price: 54.99,
      description: 'Fashionable blouse suitable for office and casual wear.',
      category: 'women',
      image: 'https://via.placeholder.com/200?text=Women+Blouse',
      rating: Rating(rate: 4.4, count: 155),
    ),
    Product(
      id: 31,
      title: 'Women\'s Jeans',
      price: 69.99,
      description: 'Trendy skinny fit jeans for modern women.',
      category: 'women',
      image: 'https://via.placeholder.com/200?text=Women+Jeans',
      rating: Rating(rate: 4.5, count: 220),
    ),
    Product(
      id: 32,
      title: 'Women\'s Cardigan',
      price: 59.99,
      description: 'Cozy cardigan perfect for layering in any season.',
      category: 'women',
      image: 'https://via.placeholder.com/200?text=Women+Cardigan',
      rating: Rating(rate: 4.3, count: 170),
    ),
    // Jewelry Products
    Product(
      id: 33,
      title: 'Gold Wedding Ring',
      price: 299.99,
      description: 'Beautiful gold wedding ring with elegant design.',
      category: 'jewelery',
      image: 'https://via.placeholder.com/200?text=Gold+Ring',
      rating: Rating(rate: 4.9, count: 120),
    ),
    Product(
      id: 34,
      title: 'Diamond Necklace',
      price: 449.99,
      description: 'Elegant diamond necklace perfect for special occasions.',
      category: 'jewelery',
      image: 'https://via.placeholder.com/200?text=Diamond+Necklace',
      rating: Rating(rate: 4.8, count: 85),
    ),
    Product(
      id: 35,
      title: 'Pearl Earrings',
      price: 129.99,
      description: 'Classic pearl earrings with sterling silver posts.',
      category: 'jewelery',
      image: 'https://via.placeholder.com/200?text=Pearl+Earrings',
      rating: Rating(rate: 4.7, count: 110),
    ),
    Product(
      id: 36,
      title: 'Silver Bracelet',
      price: 79.99,
      description: 'Stylish silver bracelet with adjustable clasp.',
      category: 'jewelery',
      image: 'https://via.placeholder.com/200?text=Silver+Bracelet',
      rating: Rating(rate: 4.5, count: 145),
    ),
    Product(
      id: 37,
      title: 'Gemstone Pendant',
      price: 199.99,
      description: 'Beautiful pendant featuring precious gemstone.',
      category: 'jewelery',
      image: 'https://via.placeholder.com/200?text=Gemstone+Pendant',
      rating: Rating(rate: 4.6, count: 95),
    ),
    Product(
      id: 38,
      title: 'Gold Anklet',
      price: 149.99,
      description: 'Delicate gold anklet perfect for beach or casual wear.',
      category: 'jewelery',
      image: 'https://via.placeholder.com/200?text=Gold+Anklet',
      rating: Rating(rate: 4.4, count: 70),
    ),
  ];

  static final List<String> mockCategories = [
    'electronics',
    'clothing',
    'accessories',
    'men',
    'women',
    'jewelery',
  ];

  static List<Product> getProductsByCategory(String category) {
    if (category.isEmpty) {
      return mockProducts;
    }
    return mockProducts.where((p) => p.category == category).toList();
  }
}
